# Generated by Django 5.2 on 2025-04-15 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_rename_image_ocrimage_front_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(upload_to='ocr_images/')),
                ('labeled_front_image', models.ImageField(blank=True, null=True, upload_to='labeled_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text_result', models.TextField(blank=True, null=True)),
                ('first_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name_ne', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_ne', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name_ne', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name_ne', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name_ne', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship_no_en', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('citizenship_no_np', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_of_birth_en', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth_np', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_place_en', models.JSONField(blank=True, null=True)),
                ('birth_place_ne', models.JSONField(blank=True, null=True)),
                ('permanent_address_en', models.JSONField(blank=True, null=True)),
                ('permanent_address_ne', models.JSONField(blank=True, null=True)),
                ('spouse_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('spouse_name_ne', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenshipBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_image', models.ImageField(upload_to='ocr_images/')),
                ('labeled_back_image', models.ImageField(blank=True, null=True, upload_to='labeled_images/')),
                ('issue_date', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date_np', models.CharField(blank=True, max_length=255, null=True)),
                ('authority_en', models.CharField(blank=True, max_length=255, null=True)),
                ('authority_ne', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('citizenship_front', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='back_data', to='ocr.citizenshipfront')),
            ],
        ),
    ]
