# Generated by Django 5.2 on 2025-04-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_citizenshipfront_citizenshipback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizenshipfront',
            name='user',
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='authority_np',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='birth_place_np',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='citizenship_no_np',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='dob_np',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='duplicate_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='ocr.ocrimage'),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='father_name_np',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='full_name_np',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='gender_np',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='issue_date_np',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='mother_name_np',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='permanent_address_np',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='spouse_name_np',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CitizenshipBack',
        ),
        migrations.DeleteModel(
            name='CitizenshipFront',
        ),
    ]
