# Generated by Django 5.2 on 2025-04-15 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_alter_ocrimage_authority_alter_ocrimage_authority_np_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_image', models.ImageField(upload_to='ocr_images/')),
                ('labeled_back_image', models.ImageField(blank=True, null=True, upload_to='labeled_images/')),
                ('issue_date_en', models.CharField(blank=True, max_length=100, null=True)),
                ('authority_en', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date_np', models.CharField(blank=True, max_length=100, null=True)),
                ('authority_np', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ocrimage',
            old_name='is_duplicate',
            new_name='is_migrated',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='authority_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='birth_place_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='citizenship_no',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='citizenship_no_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='dob_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='duplicate_reference',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='father_name_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='front_image',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='full_name_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='gender_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='issue_date_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='labeled_back_image',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='labeled_front_image',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='mother_name_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='permanent_address_np',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='scan_date',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='ocrimage',
            name='spouse_name_np',
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='back',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_image', to='ocr.citizenshipback'),
        ),
        migrations.CreateModel(
            name='CitizenshipFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(upload_to='ocr_images/')),
                ('labeled_front_image', models.ImageField(blank=True, null=True, upload_to='labeled_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text_result', models.TextField(blank=True, null=True)),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('gender_en', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenship_no_en', models.CharField(blank=True, max_length=100, null=True)),
                ('dob_en', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place_en', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_en', models.TextField(blank=True, null=True)),
                ('spouse_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('gender_np', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenship_no_np', models.CharField(blank=True, max_length=100, null=True)),
                ('dob_np', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place_np', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address_np', models.TextField(blank=True, null=True)),
                ('spouse_name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='citizenshipback',
            name='front',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='back', to='ocr.citizenshipfront'),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='front',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_image', to='ocr.citizenshipfront'),
        ),
    ]
